---
title: "Agenda"
format: html
---

# Workflows Workshop Agenda

## Day 1

| Time      | Topic                     |
|-----------|---------------------------|
| 0:00-0:25 | [Introduction & Icebreaker](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_1/day_1.html#introduction) |
| 0:25-0:35 | [Workshop Overview](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_1/day_1.html#workshop-overview) |
| 0:35-0:55 | [Markdown Basics](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_1/day_1.html#markdown) |
| **0:55-1:15** | **Break** |
| 1:15-1:20 | [Mid-session icebreaker](https://docs.google.com/document/d/1nVlmmZgp8vCHZKCMHnBm43bf-mtk7pSA1t2FLHEoyZA/edit?tab=t.0#heading=h.lwix6dbx3lr8) |
| 1:20-1:50 | [Quarto Basics](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_1/day_1.html#quarto) |
| 1:50-2:05 | [Q&A and wrap-up](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_1/day_1.html#final-reminders) |
| 2:05-2:30 | [Package and dependency installation](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_1/day_1.html#sec-prep) |

## Day 2

| Time      | Topic                     |
|-----------|---------------------------|
| 0:00-0:15 |[ Introduction & Icebreaker](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_2/day_2.html#introduction) |
| 0:15-0:35 | [{asar}: installation and overview](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_2/day_2.html#installation) |
| 0:35-1:05 | [asar::create_template()](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_2/day_2.html#asarcreate_template) |
| **1:05-1:25** | **Break** |
| 1:25-1:35 | [Mid-session icebreaker](https://docs.google.com/document/d/1nVlmmZgp8vCHZKCMHnBm43bf-mtk7pSA1t2FLHEoyZA/edit?tab=t.0#heading=h.lwix6dbx3lr8) |
| 1:35-1:55 | [stockplotr::convert_output()](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_2/day_2.html#stockplotrconvert_output) |
| **1:55-2:10** | **Break for questions** |
| 2:10-2:15 | [Mid-session icebreaker](https://docs.google.com/document/d/1nVlmmZgp8vCHZKCMHnBm43bf-mtk7pSA1t2FLHEoyZA/edit?tab=t.0#heading=h.lwix6dbx3lr8) |
| 2:15-2:35 | [Advanced workflow](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_2/day_2.html#advanced-asar-workflow) |
| **2:35-2:45** | **Break for questions** |
| 2:45-2:55 | [Standard Guidelines Discussion](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_2/day_2.html#noaa-standard-assessment-report-guidelines) |
| 2:55-3:00 | [Wrap-up](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_2/day_2.html#summary-10-mins) |

## Day 3

| Time | Topic |
|------|-------|
| 0:00-0:10 | [Icebreaker](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#icebreaker) |
| 0:10-0:20 | [{stockplotr} Overview](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#introduction-to-stockplotr) |
| 0:20-0:45 | [Create a figure + Customizing](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#example-figure) |
| **0:45-0:55** | **Break** |
| 0:55-1:05 | [Creating a table](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#example-table) |
| 1:05-1:20 | [Exporting tables and figures](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#exporting) |
| 1:20-1:50 | [Integrating {stockplotr} into the workflow](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#integrating-stockplotr-into-the-workflow) |
| **1:50-2:05** | **Break** |
| 2:05-2:15 | [Manually adding tables and figures](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#option-2-manually-adding-tablesfigures) |
| 2:15-2:40 | [Creating accessible documents](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#sec-a11y) |
| 2:40-2:50 | [Preparing for the Future](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#sec-future) |
| 2:50-3:00 | [Final remarks and questions](https://nmfs-ost.github.io/workflows-workshop/Curriculum/Day_3/day_3.html#questions-comments-feedback-and-closing) |
