---
title: "Day 3"
format: html
---

::: objectives
-   Work through a guided demo of a more complex `asar` workflow
-   Learn about the value of the `stockplotr` R package
-   Understand how to integrate `stockplotr` into an `asar`-based reporting workflow
-   Work through a guided demo of a basic `stockplotr` workflow
:::

# Introduction
## Icebreaker

Welcome! Please open the [Day 3 communal notes doc](https://docs.google.com/document/d/1SY-xwHXnJUXSXTTeaPA_UkmXXVmUK9Ol751nh6Vtjmg/edit?tab=t.vffehz79fm7y#heading=h.sfq3xaeehv64) and participate in the icebreaker exercise.

# `asar` workflow: Complex example

- Customized sections
- Reorganizing section order
- Other functions
- Latex (if there's time/interest)
  - explain limitations or potential customizations

**15 min break**

# Introduction to `stockplotr`

## `stockplotr` workflow: Basic example

- Convert output, if not done already
- Create some single plots
- How to export them
- Create and export all plots
- How to customize (changing color palette, etc.)

# Demo for a realistic, customized asar report with stockplotr plots

- create_tables_doc() and create_figures_doc() with "figures" and "tables" folders
- ensure alt text/captions work

**Time to practice, ask questions, etc.**

# Questions, comments, and feedback

Please navigate to the [Feedback](https://docs.google.com/document/d/1SY-xwHXnJUXSXTTeaPA_UkmXXVmUK9Ol751nh6Vtjmg/edit?tab=t.vffehz79fm7y#heading=h.llbcc8tygqlb) heading and tell us what you thought about today's workshop. Only 3 simple questions!

* What went well?
* What could be improved?
* What is a question you still have?