---
title: "Day 1"
format: html
---

::: objectives
-   Identify purpose and scope of workshop
-   Learn how R markdown can be used to enhance `asar` reports
-   Understand how Quarto is used to structure an `asar` report
-   Install software necessary to build an `asar` report
:::

# Introduction
## Icebreaker

Welcome! Please open the [Day 1 communal notes doc](https://docs.google.com/document/d/1SY-xwHXnJUXSXTTeaPA_UkmXXVmUK9Ol751nh6Vtjmg/edit?usp=sharing) and participate in the icebreaker exercise.

## Code of conduct

Everyone participating in this workshop is required to abide by the terms of our [Code of Conduct](https://github.com/nmfs-ost/asar/blob/main/CODE_OF_CONDUCT.md). We encourage you to contribute to a positive environment for our community by:

-   Demonstrating empathy and kindness toward other people
-   Being respectful of differing opinions, viewpoints, and experiences
-   Giving and gracefully accepting constructive feedback
-   Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
-   Focusing on what is best not just for us as individuals, but for the overall community

If you believe that someone is in violation of the Code of Conduct, please report the incident to our community leaders responsible for enforcement using [this form](https://docs.google.com/forms/d/e/1FAIpQLSftcxC8XuyoXJzrNS8cM8fXvuRWo1hnyS3TtI_VlM-XFmMYGQ/viewform).

## Who are we?

Sam Schiano and Sophie Breitbart are contractors with ECS Federal working in support of the NOAA Fisheries National Stock Assessment Program. Our work primarily focuses on stock assessment workflows by creating tools to help stock assessment scientists increase throughput. We are developing two R packages, `asar` and `stockplotr`, using an open science framework that prioritizes transparency and reproducibility.

## Materials for today's lesson

-   [Day 1 communal notes doc](https://docs.google.com/document/d/1SY-xwHXnJUXSXTTeaPA_UkmXXVmUK9Ol751nh6Vtjmg/edit?usp=sharing)
    -   Contains areas for taking notes and definitions for jargon
-   [JupyterHub workshop server](https://workshop.nmfs-openscapes.2i2c.cloud)
    -   Environment where you can code along with us, if you'd prefer
    -   All necessary packages are already installed
    -   Username: your email
    -   Password: *ask us*
-   [Sample data]()
    -   Sample model output data for coding demonstrations
################################################################
#### NOTE TO SOPHIE: add in link to sample data once ready #####
################################################################

## How to engage with us

**Questions**: Please raise your hand, or write your question in the chat, at any time. Depending on our schedule, we may ask that you save larger questions for breaks.

## Workshop overview
### Purpose and benefits to you

By the end of this workshop, we hope that you come away with the knowledge and confidence to write your next stock assessment report using a *reproducible, efficient, and transparent workflow based on `asar` and `stockplotr`*.

An `asar` workflow can help ease the following challenges:

#### Challenges faced by stock assessment scientists

- Achieving accessibility standards (section 508 compliance)
- Iteratively changing a report during review
- Meeting variable expectations for report structure and language
- Following structure of inherited assessments
- Collaborating

#### Challenges from a national perspective

- Differences in reporting among regions
- Divergent expectations from associated councils

### Scope of workshop

During this workshop, we will cover the following topics:

- Markdown language
- Quarto basics
- How to set up a reporting workflow using `asar`
- How to create semi-automated figures and tables with `stockplotr` 

### Overview of `asar`-based reporting workflow

Main steps for creating a stock assessment report with `asar`:

1. Install packages
2. Convert model output into format usable by `asar`
3. Create the report skeleton
4. Make child docs containing figures and tables (made with `stockplotr` or by other means)
5. Fill in child docs with text
6. Render report
7. Add accessibility features (PDF tags and alternative text for figures)

################################################################
#### NOTE TO SOPHIE: add in link to cheatsheet #######
################################################################
# Markdown

::: {.callout-note}
Follow along with our demo!
:::

Cover:
- Why this is useful for asar report creation
- how to open a document
- Most common uses (outlined in [markdown vignette](https://nmfs-ost.github.io/asar/articles/markdown_notation.html))
  - Parameters
  - Formatting
  - Math
  - Code chunk options (echo, include, etc.)
  - References

**15 min break**

# Quarto

::: {.callout-note}
Follow along with our demo!
:::

- Why Quarto is a good platform for asar report creation
- .qmd extension
- Skeleton setup
- how child docs work with skeleton
- Only files given paths relative to the Quarto doc will load
  - example
- yaml

# Installation

::: {.callout-tip}
## Tip

The following packages are already installed in the `asar` workspace on JupyterHub, so if you are using that space, you can skip this section.
:::

We recommend using the [`pak` R package](https://pak.r-lib.org/) to install R packages where possible, since it avoids re-downloading files if they're already present.

## `tinytex`

We recommend installing the default "bundle" of LaTeX packages via `tinytex` because 1) it's faster and 2) R *should* automatically install also-necessary LaTeX packages when they are needed, in the moment.

```r
install.packages("pak")
pak::pkg_install("rstudio/tinytex")
```

If you'd prefer, you can install the full `tinytex` bundle to ensure that all LaTeX packages will be present when you need them. This will take longer to install.

```r
install.packages("pak")
pak::pkg_install("rstudio/tinytex")
tinytex::install_tinytex(bundle = "TinyTeX-2")
```

## `asar`

Then, install `asar`.

```r
install.packages("pak")
pak::pak("nmfs-ost/asar")
```

Please see the [`asar` README](https://github.com/nmfs-ost/asar) for more installation options.

# Questions, comments, and feedback

Please navigate to the [Feedback](https://docs.google.com/document/d/1SY-xwHXnJUXSXTTeaPA_UkmXXVmUK9Ol751nh6Vtjmg/edit?tab=t.0#heading=h.llbcc8tygqlb) heading and tell us what you thought about today's workshop. Only 3 simple questions!

* What went well?
* What could be improved?
* What is a question you still have?