---
title: "Day 3"
format: html
---

::: objectives
-   Work through a guided demo of a more complex `asar` workflow
-   Learn about the value of the `stockplotr` R package
-   Understand how to integrate `stockplotr` into an `asar`-based reporting workflow
-   Work through a guided demo of a basic `stockplotr` workflow
:::

# Introduction
## Icebreaker

Welcome! Please open the [Day 3 communal notes doc](https://docs.google.com/document/d/1SY-xwHXnJUXSXTTeaPA_UkmXXVmUK9Ol751nh6Vtjmg/edit?tab=t.vffehz79fm7y#heading=h.sfq3xaeehv64) and participate in the icebreaker exercise.

# `asar` workflow: Complex example

- Customized sections
- Reorganizing section order
- Other functions
- Latex (if there's time/interest)
  - explain limitations or potential customizations

**15 min break**

# Introduction to `stockplotr`

## Installation

::: {.callout-tip}
### Tip

The following packages are already installed in the `asar` workspace on JupyterHub, so if you are using that space, you can skip this section.
:::

```r
install.packages("pak")
pak::pak("nmfs-ost/stockplotr")
```

Please see the [`stockplotr` README](https://github.com/nmfs-ost/stockplotr) for more installation options.

## `stockplotr` workflow: Basic example

### Convert output (if necessary)

First, you'll need to convert your model results using the same workflow covered yesterday: `asar::convert_output()`.

You can use the example Report.sso file uploaded to the workshop GitHub or, if you have a compatible output file, your own.

```{r}
#| label: conout-ex
#| eval: true
#| warning: false
#| messages: false
# Identify output file
output_file <- here::here("example_output", "Report.sso")
# convert the output
petrale <- asar::convert_output(output_file)
```

If you have already converted your output: great! Import it into your R environment so that you can handle it as an object like "petrale" in the chunk above.

### Create single plots



- Export single plots
- Create and export all plots
- How to customize (changing color palette, etc.)

# Demo for a realistic, customized asar report with stockplotr plots

- create_tables_doc() and create_figures_doc() with "figures" and "tables" folders
- ensure alt text/captions work

**Time to practice, ask questions, etc.**

# Questions, comments, and feedback

Please navigate to the [Feedback](https://docs.google.com/document/d/1SY-xwHXnJUXSXTTeaPA_UkmXXVmUK9Ol751nh6Vtjmg/edit?tab=t.vffehz79fm7y#heading=h.llbcc8tygqlb) heading and tell us what you thought about today's workshop. Only 3 simple questions!

* What went well?
* What could be improved?
* What is a question you still have?