---
title: "Pre-workshop checklist"
format: html
---

Here are the main steps needed to set up your environment so that you're ready to use `asar` and `stockplotr` to create a stock assessment report.

If you have any questions, please contact the [workshop organizers](https://nmfs-ost.github.io/workflows-workshop/#the-organizers).

1. Ensure that you can run [R code](https://www.r-project.org/) with a platform like RStudio, VS Code, Positron, etc.
2. Ensure you have downloaded [Quarto, version 1.6+ ](https://quarto.org/docs/get-started/) and can create Quarto documents.
3. [Create a new Github repo](https://happygitwithr.com/rstudio-git-github.html#make-a-repo-on-github-1) for the workshop.
4. [Clone your repo and set up an RStudio Project](https://happygitwithr.com/rstudio-git-github.html#clone-the-test-github-repository-to-your-computer-via-rstudio).
5. Run the following code to get two essential files from the workflows-workshop github repo:

- input data file "Report.sso" will save to a "example_output" folder in your home directory
- example plot file "landings_fig_png.png" will save to a "example_plots" folder in your home directory

```{r eval=FALSE, message=FALSE}
# Function to obtain two files used during workshop
get_workshop_files <- function(dest_folder,
                               dest_file,
                               url){
  if (!file.exists(dest_folder)) {
    dir.create(dest_folder)
  }
  if (!file.exists(dest_file)) {
    cli::cli_alert_info("📥 Downloading {dest_file}...")
    download.file(url, dest_file, mode = "wb")
    message("✅ Download complete.")
  } else {
    cli::cli_alert_info("✅ File already exists: {dest_file}")
  }
}

# Obtain example output file
get_workshop_files(
  dest_folder = file.path(here::here("example_output")),
  dest_file = file.path(here::here("example_output", "Report.sso")),
  url = "https://github.com/nmfs-ost/workflows-workshop/blob/main/example_output/Report.sso"
  )

# Obtain example figure file
get_workshop_files(
  dest_folder = file.path(here::here("example_plots")),
  dest_file = file.path(here::here("example_plots", "landings_fig_png.png")),
  url = "https://raw.githubusercontent.com/nmfs-ost/workflows-workshop/main/example_output/Report.sso"
  )
```

6. Install important R packages

::: {.callout-tip}
## Tip

The following packages are already installed in the `asar` workspace on JupyterHub, so if you are using that space, you can skip this section.
:::

We recommend using the [`pak` R package](https://pak.r-lib.org/) to install R packages where possible, since it avoids re-downloading files if they're already present.

```r
install.packages("pak")
```

* `asar`

```r
pak::pak("nmfs-ost/asar")
```

Please see the [`asar` README](https://github.com/nmfs-ost/asar) for more installation options.

* `stockplotr`

```r
pak::pak("nmfs-ost/stockplotr")
```

Please see the [`stockplotr` README](https://github.com/nmfs-ost/stockplotr) for more installation options.

* `tinytex`

We recommend installing the full `tinytex` bundle to ensure that all LaTeX packages will be present when you need them. **This will take ~30 minutes to complete.**

```r
pak::pkg_install("rstudio/tinytex")
tinytex::install_tinytex(bundle = "TinyTeX-2")
```